const AUTO_SLUG_PATTERN = /^\/(?:20\d{2}[0-9-]*|[0-9-]+)\/$/;

const PHRASE_MAP: Array<[string, string]> = [
  ["口臭ケア", "oralcare"],
  ["フェイスクリーム", "facecream"],
  ["シートマスク", "sheetmask"],
  ["フェイスパック", "facepack"],
  ["化粧水", "lotion"],
  ["美容液", "serum"],
  ["クレンジング", "cleansing"],
  ["メンズ", "mens"],
  ["ビタミン", "vitamin"],
  ["美白", "whitening"],
  ["保湿", "moisturizing"],
  ["敏感肌", "sensitive-skin"],
  ["乾燥肌", "dry-skin"],
  ["オイリー肌", "oily-skin"],
  ["ニキビ", "acne"],
  ["お土産", "omiyage"],
  ["名物", "meibutsu"],
  ["おすすめ", "osusume"],
  ["焼肉用", "yakiniku"],
  ["牛肉", "beef"],
  ["ダイエット", "diet"],
  ["スリッパ", "slippers"],
  ["北海道", "hokkaido"],
  ["東京", "tokyo"],
  ["大阪", "osaka"],
  ["京都", "kyoto"],
  ["名古屋", "nagoya"],
  ["金沢", "kanazawa"],
  ["広島", "hiroshima"],
  ["沖縄", "okinawa"],
  ["佐賀", "saga"],
  ["鹿児島", "kagoshima"],
  ["宮崎", "miyazaki"],
  ["大分", "oita"],
  ["熊本", "kumamoto"],
  ["長崎", "nagasaki"],
  ["福岡", "fukuoka"],
];

function normalizePathname(slug: string) {
  const trimmed = slug.trim();
  if (!trimmed) return "/";
  const withLeadingSlash = trimmed.startsWith("/") ? trimmed : `/${trimmed}`;
  if (withLeadingSlash === "/") return withLeadingSlash;
  return `${withLeadingSlash.replace(/\/+$/, "")}/`;
}

function transliterateJapanese(input: string) {
  let result = input;

  for (const [needle, replacement] of PHRASE_MAP) {
    result = result.split(needle).join(` ${replacement} `);
  }

  return result
    .toLowerCase()
    .replace(/[＆&+/]/g, " ")
    .replace(/[・]/g, " ")
    .replace(/[()（）［］【】]/g, " ")
    .replace(/[^a-z0-9\s-]/g, " ")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function buildSlugCandidate(targetKeyword?: string | null, title?: string | null) {
  const base = transliterateJapanese(targetKeyword || title || "");
  if (!base) return null;
  if (/(?:^|-)osusume(?:-|$)/.test(base) || /(?:^|-)guide(?:-|$)/.test(base)) {
    return base;
  }
  return `${base}-guide`;
}

export function isAutoGeneratedSlug(slug: string) {
  return AUTO_SLUG_PATTERN.test(normalizePathname(slug));
}

export function normalizeArticleSlug(input: string) {
  const cleaned = input
    .trim()
    .toLowerCase()
    .replace(/^\/+|\/+$/g, "")
    .replace(/[^a-z0-9/-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/\/+/g, "/")
    .replace(/^-+|-+$/g, "");

  return cleaned ? `/${cleaned}/` : "/";
}

export function getPreferredArticleSlug(params: {
  currentSlug: string;
  targetKeyword?: string | null;
  title?: string | null;
}) {
  const currentSlug = normalizePathname(params.currentSlug);
  if (!isAutoGeneratedSlug(currentSlug)) {
    return currentSlug;
  }

  const candidate = buildSlugCandidate(params.targetKeyword, params.title);
  if (!candidate) {
    return currentSlug;
  }

  return normalizeArticleSlug(candidate);
}
